[project]
name = "hato-bot-go"
version = "1.0"
description = "愛嬌のあるBot"
requires-python = "==3.14.3"
dependencies = []

[dependency-groups]
dev = [
  "pre-commit==4.5.1",
]

[tool.uv]
required-version = "0.8.3"
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
